changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: New features
      labels:
        - enhancement
        - feature
    - title: Bug fixes
      labels:
        - bug
        - fix
    - title: Pets and assets
      labels:
        - pet
        - assets
    - title: Documentation and maintenance
      labels:
        - documentation
        - dependencies
        - maintenance
    - title: Other changes
      labels:
        - "*"
